version: '3'
services:

  backend:
    build:
      context: backend/
      args:
        # A (THE?) way to pass args from command line via docker-compose to Dockerfile:
        # Set envvar, and use it immediately in docker-compose.
        # Win CMD (not tested): set ENCODE_ALL="true" && docker-compose up ...
        # PowerShell: $env:ENCODE_ALL="true" ; docker-compose up ...
        # Linux (not tested): ENCODE_ALL=true docker-compose up ...
        - ENCODE_ALL
    volumes:
      - ./backend/corpora:/opt/host_corpora
    ports:
      # Korp backend server
      - "1234:1234"

  frontend:
    build: frontend/
    depends_on:
      - backend
    volumes:
      - ./frontend:/opt/korp-frontend-config
    ports:
      # Korp frontend server
      - "9111:9111"
