version: '3'
services:
  backend:
    build: backend/
    volumes:
      - ${CORPORA_DIR}:/opt/corpora
    ports:
      # Korp backend server
      - "1234:1234"
  frontend:
    build: frontend/
    depends_on:
      - backend
    volumes:
      - ${KORP_FRONTEND_CONFIG_DIR}:/opt/korp-frontend-config
    ports:
      # Korp frontend server
      - "9111:9111"
